### ISSUE TITLE
Tool stack constructed using non-modifiable tool

### ISSUE THREAD

**Issue by MrZora** [RCXcrafter/Materialis#25]
`[Render thread/WARN] [tconstruct/]: Tool stack constructed using non-modifiable tool, this may cause issues as it has no NBT. Stacktrace can be disabled in config.
java.lang.Exception: Stack trace
	at slimeknights.tconstruct.library.tools.nbt.ToolStack.from(ToolStack.java:145) ~[TConstruct-1.18.2-3.6.2.92.jar%23154!/:1.18.2-3.6.2.92]
	at slimeknights.tconstruct.library.tools.nbt.ToolStack.from(ToolStack.java:163) ~[TConstruct-1.18.2-3.6.2.92.jar%23154!/:1.18.2-3.6.2.92]
	at com.rcx.materialis.modifiers.EngineersGogglesModifier.wearingGoggledHelmet(EngineersGogglesModifier.java:19) ~[materialis-1.18.2-2.7.1.jar%23124!/:1.18.2-2.7.1]
	at com.simibubi.create.content.contraptions.goggles.GogglesItem.isWearingGoggles(GogglesItem.java:53) ~[create-1.18.2-0.5.0.h.jar%2382!/:0.5.0.h]
	at com.simibubi.create.content.contraptions.goggles.GoggleOverlayRenderer.renderOverlay(GoggleOverlayRenderer.java:83) ~[create-1.18.2-0.5.0.h.jar%2382!/:0.5.0.h]
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$render$26(ForgeIngameGui.java:348) ~[forge-1.18.2-40.2.0-universal.jar%23170!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:342) ~[forge-1.18.2-40.2.0-universal.jar%23170!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:870) ~[client-1.18.2-20220404.173914-srg.jar%23165!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23165!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23165!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23165!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2351!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]`

Been having the log fill up with this error, not sure if it's because of a Tinker's Construct or Create update.

**Comment by Bulwarini** [comment]
Same thing right here

**Comment by KnightMiner** [comment]
Worth saying, the warning (which the log marks as warn) is technically "caused" by a Tinkers' Construct update. However, its simply logging something that was silently ignored before (with some possible nasty side-effects for ignoring it). Materialis seems to be creating a `ToolStack` from an item without checking if its a valid tool first, which can lead to putting empty NBT tags on items (messes with items stacking with each other, in the worst cases this could be on an item stack in the inventory, e.g. from a wrongly implemented crafting recipe)

If you are getting that warning, it means you are in the TiC update the prevents the most common issue (the not stacking, which logs that warning instead). It still could potentially be a bug in the mod's (Materialis's) code as that class relies on the NBT existing, but looks like in Materialis's case they just want to check for a modifier level. Could fix with a tag check first (bit faster than a NBT check) or alternatively just using the `ModifierUtil` method (faster than `ToolStack` for a simple query).

**Comment by Bulwarini** [comment]
well this thing is filling up my log way to fast in minutes its taking up a whole lot of space. Any possible way to disable warining fully?

**Comment by KnightMiner** [comment]
There is no feature to do so currently. So you have to wait on an update from either Materialis or Tinkers in any case.

**Comment by RCXcrafter** [comment]
Fixed in materialis 2.7.2, sorry for the delay
